version: '3'

services:
  mongo:
    container_name: $MONGO_CONTAINER
    image: mongo
    networks:
      - mongo
    env_file:
      - .env
    environment:
      - MONGO_PORT=$MONGO_PORT
      - MONGO_DB=$MONGO_DB
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    restart: always

  app:
    image: node:12.18.4
    container_name: $CONTAINER_NAME
    working_dir: /usr/app
    volumes:
      - .:/usr/app
    networks:
      - mongo
    env_file:
      - .env
    ports:
      - 3333:3333
    depends_on:
      - mongo
    restart: always
    command: bash -c "chown -R node:node /usr/app && yarn && yarn start"

networks:
  mongo:
    driver: bridge
